export default {
	info: [
		{
			dia: "(28/09) Quarta-feira",
			id: "28-09",
			programacao: [
				// {
				// 	inicio: "8:00",
				// 	fim: "12:00",
				// 	titulo: "Minicurso A1",
				// 	palestrante: "A definir",
				// 	descricao: "A definir (saiba mais no nosso instagram)",
				// 	tipo: "minicurso",
				// },
				// {
				// 	inicio: "8:00",
				// 	fim: "12:00",
				// 	titulo: "Minicurso A2",
				// 	palestrante: "A definir",
				// 	descricao: "A definir (saiba mais no nosso instagram)",
				// 	tipo: "minicurso",
				// },
				// {
				// 	inicio: "8:00",
				// 	fim: "12:00",
				// 	titulo: "Minicurso A3",
				// 	palestrante: "A definir",
				// 	descricao: "A definir (saiba mais no nosso instagram)",
				// 	tipo: "minicurso",
				// },
				// {
				// 	inicio: "8:00",
				// 	fim: "12:00",
				// 	titulo: "Minicurso A4",
				// 	palestrante: "A definir",
				// 	descricao: "A definir (saiba mais no nosso instagram)",
				// 	tipo: "minicurso",
				// },
				// {
				// 	inicio: "12:00",
				// 	fim: "13:30",
				// 	titulo: "Almoço",
				// 	tipo: "pausa",
				// },
				{
					inicio: "13:30",
					fim: "14:00",
					titulo: "Abertura",
					descricao: "A definir (saiba mais no nosso instagram)",
				},
				{
					// inicio: "14:00",
					// fim: "15:30",
					titulo: "Introdução ao MetaVerso",
					palestrante: "Ingrid Winkler",
					descricao: "Palestra: Ingrid Winkler",
					tipo: "palestra",
					link: "#IngridWinkler",
				},
				{
					inicio: "15:30",
					fim: "16:00",
					titulo: "Coffee Break",
					tipo: "pausa",
				},
				{
					// inicio: "16:00",
					// fim: "17:30",
					titulo: "Palestra 2",
					palestrante: "Paula Dornhofer Paro Costa",
					descricao: "Paula Dornhofer Paro Costa",
					tipo: "palestra",
					link: "#PaulaDornhofer",
				},
				{
					inicio: "17:30",
					fim: "20:00",
					titulo: "Intervalo",
					tipo: "pausa",
				},
				{
					inicio: "20:00",
					fim: "21:00",
					titulo: "Live 1",
					palestrante: "A definir",
					descricao: "A definir (saiba mais no nosso instagram)",
					tipo: "live",
				},
				{
					inicio: "21:00",
					fim: "22:00",
					titulo: "Live 2",
					palestrante: "A definir",
					descricao: "A definir (saiba mais no nosso instagram)",
					tipo: "live",
				},
			],
		},
		{
			dia: "(29/09) Quinta-feira",
			id: "29-09",
			programacao: [
				{
					inicio: "08:00",
					fim: "12:00",
					titulo: "Jogos com Lua",
					palestrante: "Professor Elinaldo",
					descricao: "Minicurso: Professor Elinaldo",
					tipo: "minicurso",
					link: "#Elinaldo",
				},
				{
					inicio: "08:00",
					fim: "12:00",
					titulo: "Web Design (UI&UX)",
					palestrante: "Igor Rocha",
					descricao: `Minicurso: Aprenda a projetar interfaces de usuário e experiência do usuário, 
					com o objetivo de criar um site ou aplicativo que seja agradável e fácil de usar. Você aprenderá 
					a usar o Figma (desde o básico) no decorrer do minicurso.`,
					tipo: "minicurso",
					link: "#IgorRocha",
				},
				{
					inicio: "08:00",
					fim: "12:00",
					titulo: "Análise de Pontos por Função e Métodos Ágeis",
					palestrante: "Napoleão Batista Lemos Filho",
					descricao: `Minicurso: Descrição do minicurso`,
					tipo: "minicurso",
					link: "#NapoleaoBatista",
				},
				{
					inicio: "12:00",
					fim: "13:30",
					titulo: "Almoço",
					tipo: "pausa",
				},
				{
					inicio: "13:30",
					fim: "14:00",
					titulo: "Lançamento do Livro",
				},
				{
					// inicio: "14:00",
					// fim: "15:30",
					titulo: "Palestra 3",
					palestrante: "Flavio Shigeo Yamamoto",
					descricao: "Palestra: Descrição da palestra",
					tipo: "palestra",
					link: "#FlavioShigeo",
				},
				{
					inicio: "15:30",
					fim: "16:00",
					titulo: "Coffee Break",
					tipo: "pausa",
				},
				{
					// inicio: "16:00",
					// fim: "17:30",
					titulo: "Palestra 4",
					palestrante: "Katia Vaskys",
					descricao: "Palestra: Descrição da palestra",
					tipo: "palestra",
					link: "#KatiaVaskys",
				},
				{
					inicio: "18:00",
					fim: "20:00",
					titulo: "Intervalo",
					tipo: "pausa",
				},
				{
					inicio: "20:00",
					fim: "21:00",
					titulo: "Ciência de Dados",
					palestrante: "João e Paulo",
					descricao: "Live: Descrição da live",
					tipo: "live",
				},
				{
					inicio: "21:00",
					fim: "22:00",
					titulo: "MetaVerso",
					palestrante: "Kevin Talarico",
					descricao: "Live: Descrição da live",
					tipo: "live",
				},
			],
		},
		{
			dia: "(30/09) Sexta-feira",
			id: "30-09",
			programacao: [
				{
					inicio: "08:00",
					fim: "12:00",
					titulo: "Blockchain: Criação de contrato",
					palestrante: "Henrique Serra",
					descricao:
						"Minicurso: Criação de contrato e integração com app react / Henrique Serra",
					tipo: "minicurso",
					link: "#HenriqueSerra",
				},
				{
					inicio: "08:00",
					fim: "12:00",
					titulo: "Mobile Design (UI&UX)",
					palestrante: "Igor Rocha",
					descricao: `Minicurso: Veja na prática como desenvolver uma interface de um aplicativo 
					voltado ao MetaVerso. Para esse minicurso, você precisará ter participado do primeiro 
					minicurso de Figma, ou já possuir experiência no mesmo.`,
					tipo: "minicurso",
					link: "#IgorRocha",
				},
				{
					inicio: "12:00",
					fim: "13:30",
					titulo: "Almoço",
					tipo: "pausa",
				},
				{
					// inicio: "14:00",
					// fim: "15:30",
					titulo: "Allan Edgard",
					palestrante: "Allan Edgard Silva Freitas",
					descricao: "Palestra: Descrição da palestra",
					tipo: "palestra",
					link: "#AllanEdgard",
				},
				{
					inicio: "15:30",
					fim: "16:00",
					titulo: "Coffee Break",
					tipo: "pausa",
				},
				{
					// inicio: "16:00",
					// fim: "17:30",
					titulo: "Palestra 6",
					palestrante: "A definir",
					descricao: "A definir (saiba mais no nosso instagram)",
					tipo: "palestra",
				},
				{
					inicio: "18:00",
					fim: "20:00",
					titulo: "Intervalo",
					tipo: "pausa",
				},
				{
					inicio: "20:00",
					fim: "21:00",
					titulo: "Live 5",
					palestrante: "A definir",
					descricao: "A definir (saiba mais no nosso instagram)",
					tipo: "live",
				},
				{
					inicio: "21:00",
					fim: "22:00",
					titulo: "Live 6",
					palestrante: "A definir",
					descricao: "A definir (saiba mais no nosso instagram)",
					tipo: "live",
				},
			],
		},
		{
			dia: "(01/10) Sábado",
			id: "01-10",
			programacao: [
				{
					inicio: "09:00",
					fim: "11:00",
					titulo: "Aquecimento - CPU",
					palestrante: "Link para inscrição",
					link: "https://cpu.tecnojr.com.br/",
					descricao:
						"Aquecimento para o Campeonato de Programação Universitária",
					tipo: "live",
				},
				{
					inicio: "11:00",
					fim: "13:30",
					titulo: "Almoço",
					tipo: "pausa",
				},
				{
					inicio: "13:30",
					fim: "17:30",
					titulo: "CPU",
					palestrante: "Link para inscrição",
					link: "https://cpu.tecnojr.com.br/",
					tipo: "live",
				},
				{
					// inicio: "17:30",
					// fim: "18:00",
					titulo: "Premiação",
					tipo: "palestra",
				},
			],
		},
	],
}
